//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clippy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clippy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated already running instance of the application.
        /// </summary>
        internal static string ActivatedExistedProcess {
            get {
                return ResourceManager.GetString("ActivatedExistedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all marks.
        /// </summary>
        internal static string allMarks {
            get {
                return ResourceManager.GetString("allMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all types.
        /// </summary>
        internal static string allTypes {
            get {
                return ResourceManager.GetString("allTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application &quot;{0}&quot; added to ignore list, which can be edited in Settings window.
        /// </summary>
        internal static string ApplicationAddedToIgnoreList {
            get {
                return ResourceManager.GetString("ApplicationAddedToIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string AutoSelectMatch {
            get {
                return ResourceManager.GetString("AutoSelectMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string AutoSelectMatchedClip {
            get {
                return ResourceManager.GetString("AutoSelectMatchedClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string ByteUnit {
            get {
                return ResourceManager.GetString("ByteUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to paste into window having higher priviledges. Try run program as administrator..
        /// </summary>
        internal static string CantPasteInElevatedWindow {
            get {
                return ResourceManager.GetString("CantPasteInElevatedWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CaseConversionMode {
            get {
                return ResourceManager.GetString("CaseConversionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С.
        /// </summary>
        internal static string CharUnit {
            get {
                return ResourceManager.GetString("CharUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear1 {
            get {
                object obj = ResourceManager.GetObject("clear1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClearFilter {
            get {
                object obj = ResourceManager.GetObject("ClearFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon clipboard {
            get {
                object obj = ResourceManager.GetObject("clipboard", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip file already opened and blocked.
        /// </summary>
        internal static string ClipFileAlreadyOpened {
            get {
                return ResourceManager.GetString("ClipFileAlreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied clip ({2}) was not captured. Too big size {0}KB &gt; {1}KB (set in settings).
        /// </summary>
        internal static string ClipWasNotCaptured {
            get {
                return ResourceManager.GetString("ClipWasNotCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Columns {
            get {
                object obj = ResourceManager.GetObject("Columns", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Compare {
            get {
                object obj = ResourceManager.GetObject("Compare", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete all non favorite clips?.
        /// </summary>
        internal static string ConfirmDeleteAllNonFavorite {
            get {
                return ResourceManager.GetString("ConfirmDeleteAllNonFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete selected clips?.
        /// </summary>
        internal static string ConfirmDeleteSelectedClips {
            get {
                return ResourceManager.GetString("ConfirmDeleteSelectedClips", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn’t register the global hot key.
        /// </summary>
        internal static string CouldNotRegisterHotkey {
            get {
                return ResourceManager.GetString("CouldNotRegisterHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show rest of text.
        /// </summary>
        internal static string CutMarker {
            get {
                return ResourceManager.GetString("CutMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clippy.litedb.
        /// </summary>
        internal static string DBShortFilename {
            get {
                return ResourceManager.GetString("DBShortFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DelimiterForTextJoin {
            get {
                return ResourceManager.GetString("DelimiterForTextJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duplicate {
            get {
                object obj = ResourceManager.GetObject("Duplicate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit clip title.
        /// </summary>
        internal static string EditClipTitle {
            get {
                return ResourceManager.GetString("EditClipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END.
        /// </summary>
        internal static string EndMarker {
            get {
                return ResourceManager.GetString("EndMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip was not captured due to clipboard read error.
        /// </summary>
        internal static string ErrorReadingClipboard {
            get {
                return ResourceManager.GetString("ErrorReadingClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye {
            get {
                object obj = ResourceManager.GetObject("eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed change database file encryption.
        /// </summary>
        internal static string FailedChangeDatabaseFieEncryption {
            get {
                return ResourceManager.GetString("FailedChangeDatabaseFieEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read data in format &quot;{0}&quot; from clipboard..
        /// </summary>
        internal static string FailedToReadFormatFromClipboard {
            get {
                return ResourceManager.GetString("FailedToReadFormatFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write clipboard. It is locked by window &quot;{0}&quot; application &quot;{1}&quot;.
        /// </summary>
        internal static string FailedToWriteClipboard {
            get {
                return ResourceManager.GetString("FailedToWriteClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorite.
        /// </summary>
        internal static string favorite {
            get {
                return ResourceManager.GetString("favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filename.
        /// </summary>
        internal static string filename {
            get {
                return ResourceManager.GetString("filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Filter1 {
            get {
                object obj = ResourceManager.GetObject("Filter1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered {0}.
        /// </summary>
        internal static string FilteredStatusText {
            get {
                return ResourceManager.GetString("FilteredStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string FilterListBySearchString {
            get {
                return ResourceManager.GetString("FilterListBySearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindNext {
            get {
                object obj = ResourceManager.GetObject("FindNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindOptions {
            get {
                object obj = ResourceManager.GetObject("FindOptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindPrevious {
            get {
                object obj = ResourceManager.GetObject("FindPrevious", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FixedWidthFont {
            get {
                object obj = ResourceManager.GetObject("FixedWidthFont", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global hotkeys.
        /// </summary>
        internal static string GlobalHotkeys {
            get {
                return ResourceManager.GetString("GlobalHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear string to use auto title.
        /// </summary>
        internal static string HowUseAutoTitle {
            get {
                return ResourceManager.GetString("HowUseAutoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html.
        /// </summary>
        internal static string html {
            get {
                return ResourceManager.GetString("html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to img.
        /// </summary>
        internal static string img {
            get {
                return ResourceManager.GetString("img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string KiloByteUnit {
            get {
                return ResourceManager.GetString("KiloByteUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For full language change you may need to restart program.
        /// </summary>
        internal static string LangRestart {
            get {
                return ResourceManager.GetString("LangRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last clip was captured twice before compare.
        /// </summary>
        internal static string LastClipWasMultiCaptured {
            get {
                return ResourceManager.GetString("LastClipWasMultiCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MarkFavorite {
            get {
                object obj = ResourceManager.GetObject("MarkFavorite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string MegaByteUnit {
            get {
                return ResourceManager.GetString("MegaByteUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard monitoring now is OFF.
        /// </summary>
        internal static string MonitoringOFF {
            get {
                return ResourceManager.GetString("MonitoringOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard monitoring now is ON.
        /// </summary>
        internal static string MonitoringON {
            get {
                return ResourceManager.GetString("MonitoringON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MonospacedFont {
            get {
                return ResourceManager.GetString("MonospacedFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveCopiedClipToTop {
            get {
                object obj = ResourceManager.GetObject("MoveCopiedClipToTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available. To update use button in top command bar..
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next сlip.
        /// </summary>
        internal static string NextClip {
            get {
                return ResourceManager.GetString("NextClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no target window.
        /// </summary>
        internal static string NoActiveWindow {
            get {
                return ResourceManager.GetString("NoActiveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No capture.
        /// </summary>
        internal static string NoCapture {
            get {
                return ResourceManager.GetString("NoCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supported text compare application was found. Now we open website to get free one..
        /// </summary>
        internal static string NoSupportedTextCompareApplication {
            get {
                return ResourceManager.GetString("NoSupportedTextCompareApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenFile {
            get {
                object obj = ResourceManager.GetObject("OpenFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenWith {
            get {
                object obj = ResourceManager.GetObject("OpenWith", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just pasted clip is the last.
        /// </summary>
        internal static string PastedLastClip {
            get {
                return ResourceManager.GetString("PastedLastClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel.
        /// </summary>
        internal static string PixelFormat {
            get {
                return ResourceManager.GetString("PixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to reset settings to default values?.
        /// </summary>
        internal static string QuestionResetSettings {
            get {
                return ResourceManager.GetString("QuestionResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtf.
        /// </summary>
        internal static string rtf {
            get {
                return ResourceManager.GetString("rtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string SearchAllFields {
            get {
                return ResourceManager.GetString("SearchAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string SearchCaseSensitive {
            get {
                return ResourceManager.GetString("SearchCaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string SearchIgnoreBigTexts {
            get {
                return ResourceManager.GetString("SearchIgnoreBigTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string SearchWildcards {
            get {
                return ResourceManager.GetString("SearchWildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string SearchWordsIndependently {
            get {
                return ResourceManager.GetString("SearchWordsIndependently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ShowNativeTextFormatting {
            get {
                return ResourceManager.GetString("ShowNativeTextFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ShowSecondaryColumns {
            get {
                return ResourceManager.GetString("ShowSecondaryColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target application.
        /// </summary>
        internal static string TargetApp {
            get {
                return ResourceManager.GetString("TargetApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target window.
        /// </summary>
        internal static string TargetWindow {
            get {
                return ResourceManager.GetString("TargetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        internal static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *email.
        /// </summary>
        internal static string text_email {
            get {
                return ResourceManager.GetString("text_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *filename.
        /// </summary>
        internal static string text_filename {
            get {
                return ResourceManager.GetString("text_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *number.
        /// </summary>
        internal static string text_number {
            get {
                return ResourceManager.GetString("text_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *phone.
        /// </summary>
        internal static string text_phone {
            get {
                return ResourceManager.GetString("text_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *time.
        /// </summary>
        internal static string text_time {
            get {
                return ResourceManager.GetString("text_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *url.
        /// </summary>
        internal static string text_url {
            get {
                return ResourceManager.GetString("text_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *url-image.
        /// </summary>
        internal static string text_url_image {
            get {
                return ResourceManager.GetString("text_url_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *url-video.
        /// </summary>
        internal static string text_url_video {
            get {
                return ResourceManager.GetString("text_url_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextFormatting {
            get {
                object obj = ResourceManager.GetObject("TextFormatting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too big text for sending via channel. Max size - 10000 chars..
        /// </summary>
        internal static string TooBigClipForChannel {
            get {
                return ResourceManager.GetString("TooBigClipForChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Top2 {
            get {
                object obj = ResourceManager.GetObject("Top2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TopMostWindow {
            get {
                object obj = ResourceManager.GetObject("TopMostWindow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TypeFile {
            get {
                object obj = ResourceManager.GetObject("TypeFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TypeHtml {
            get {
                object obj = ResourceManager.GetObject("TypeHtml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TypeImg {
            get {
                object obj = ResourceManager.GetObject("TypeImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TypeRtf {
            get {
                object obj = ResourceManager.GetObject("TypeRtf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TypeText {
            get {
                object obj = ResourceManager.GetObject("TypeText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnmarkFavorite {
            get {
                object obj = ResourceManager.GetObject("UnmarkFavorite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update to.
        /// </summary>
        internal static string UpdateTo {
            get {
                return ResourceManager.GetString("UpdateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to used.
        /// </summary>
        internal static string used {
            get {
                return ResourceManager.GetString("used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.14.
        /// </summary>
        internal static string VersionValue {
            get {
                return ResourceManager.GetString("VersionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual clip weight (number of digits in number representing visual clip size).
        /// </summary>
        internal static string VisualWeightTooltip {
            get {
                return ResourceManager.GetString("VisualWeightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WordWrap {
            get {
                object obj = ResourceManager.GetObject("WordWrap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file format.
        /// </summary>
        internal static string WrongFileFormat {
            get {
                return ResourceManager.GetString("WrongFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
