name: Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - uses: microsoft/setup-msbuild@v1.1

    - uses: actions/checkout@v2

    - name: Build
      run: |
        dotnet restore
        msbuild /t:publish /p:Configuration=Release /p:RuntimeIdentifier=win-x64 /p:TargetFramework=net6.0-windows /p:TargetPlatformVersion=8.0 /p:PublishSingleFile=true /p:PublishReadyToRun=false /p:SelfContained=false
                
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Clippy
        path: |
          D:\a\Clippy\Clippy\bin\Release\net6.0-windows8.0\publish\*

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          D:\a\Clippy\Clippy\bin\Release\net6.0-windows8.0\publish\*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
        
