name: .NET Core Desktop

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - uses: microsoft/setup-msbuild@v1.1

    - uses: actions/checkout@v3

    - name: Build
      run: |
        dotnet restore
        msbuild Clippy.sln /t:publish /p:Platform="Any CPU" /p:RuntimeIdentifier=win-x64 p:/TargetFramework=net6.0 /p:PublishSingleFile=true /p:PublishReadyToRun=false /p:SelfContained=false

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Clippy
        path: |
          D:\a\Clippy\Clippy\bin\Publish\**\*

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          D:\a\Clippy\Clippy\bin\Publish\**\*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       

