name: Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - uses: microsoft/setup-msbuild@v1.1

    - uses: actions/checkout@v2

    - name: Build
      run: |
        dotnet restore
        msbuild /t:publish
